### ISSUE TITLE
Facebook SDK issue

### ISSUE THREAD

**Issue by camfindlay** [wilr/silverstripe-facebookconnect#18]
When installing via composer the master of the facebook sdk is cloned https://github.com/facebook/facebook-php-sdk-v4 - this now excludes some of the classes used by this module. I am thinking perhaps the sdk has changed since the module was last updated?

Doing a git checkout of the 4.0-dev branch seems to checkout the correct dependancies.

**Comment by anselmdk** [comment]
Just had that issue and required the following in my `composer.json`, which fixed it: `"facebook/php-sdk-v4": "4.0"`
@wilr I could to a pull request on it.

**Comment by anselmdk** [comment]
Actually this seems to be the way to to: https://github.com/hpmewes/silverstripe-facebookconnect/commit/acef97d0fc17d5eac12decbe5a804ba517c373db
