### ISSUE TITLE
Class 'Facebook\FacebookSession' not found on fresh install

### ISSUE THREAD

**Issue by promotion** [wilr/silverstripe-facebookconnect#20]
Hi , 
fresh install (manual or composer based) of 3.1.13 
after instal/build/flush , adding link to login would cause error:

Class 'Facebook\FacebookSession' not found in /myprojectpath/facebookconnect/code/extensions/FacebookControllerExtension.php on line 100

CentOS 6 / PHP 5.4.4 
Help please.
PS - found same issue on forum - https://www.silverstripe.org/community/forums/general-questions/show/76585?start=0

**Comment by promotion** [comment]
This is an issue of FB API version - had to download 4.0 manually

**Comment by wilr** [comment]
Should not be resolved.
