### ISSUE TITLE
Not getting FB user details

### ISSUE THREAD

**Issue by DorsaiNZ** [wilr/silverstripe-facebookconnect#21]
Hi,

Having succesfully negotiated installing the plugin and getting the older FB SDK so it works, I am having an issue with getting the FB details into the Member table.

While the FacebookUID field get filled in, nothing else comes across from FB. The first time a user logins via FB it indicates that it is accessing email, public_profile and user_friends. I have manually set the sync_member_details to true, and left it out - it doesn't make a difference either way.

Additionally although I have set: member_groups: 'Shoppers' the user does not get added to this group.

Any pointers on where I am going wrong?

Cheers
D

**Comment by jcop007** [comment]
Hi D
We've experienced exactly the same problem. We switched to FB SDK dev-4.0-dev and it basically works, logging the user in, but as you found it is only storing the FaceBookUID on the member record.
The latest FB SDK 5.0-dev  is 288 commits ahead so I was wondering if dev-4.0-dev is just too out of date now and isn't working properly?  
JC

**Comment by DorsaiNZ** [comment]
Hey JC,

Thanks for the feedback - nice to know I'm not the only one. 

For the moment I am going to leave it as is - just having the user login using FB is enough (barely) that I can continue with the rest of the site. I will have to come back to this later. Unless someone else has an idea on how to deal with this I suspect I may have to end up writing my own functions to get the FB data. At any rate I will let you know what I came up with.

Cheers
D

**Comment by jcop007** [comment]
Hi D
We managed to get it working by passing through an array of fields that we wanted to the FacebookRequest get GraphObect call in the controllers/FacebookConnectAuthCallback.php line 52.  e.g 
$params = array("fields"=>"email,first_name,last_name");
				$user = (new FacebookRequest(
					$session, 'GET', '/me', $params
				))->execute()->getGraphObject(GraphUser::className());
Hope that helps.  
JC

**Comment by DorsaiNZ** [comment]
Hi JC,

That worked perfectly thanks. Where do I send the beer?

Cheers
D

**Comment by wilr** [comment]
Someone able to put together a PR?

**Comment by jcop007** [comment]
Hi D, 
Great!  No worries, just nice to be part of a community.  

Hi Wilr
I can put together a pull request.
Thanks for making this module available btw,
JC

**Comment by wilr** [comment]
PR merged and fixed. You can now use the config API to define the fields.
