### ISSUE TITLE
PAGE NOT FOUND after login

### ISSUE THREAD

**Issue by Edvardas-idea** [wilr/silverstripe-facebookconnect#29]
Hey, i'm getting 404 after i login and redirect back, could it be because i'm trying to test it localy ?

**Comment by wilr** [comment]
Testing locally should be fine. What is the URL you are being returned too? Make sure you have flushed after installing the module.

**Comment by Spambanjo** [comment]
I have the same issue. It's got me stumped

**Comment by Edvardas-idea** [comment]
Yep, same thing as Spanbanjo says. url looks like : http://project.local/FacebookConnectAuthCallback/connect?code={CODE_REMOVED}&state={CODE_REMOVED}

**Comment by Edvardas-idea** [comment]
Definetly something with the new SS version, with older SS working fine, but i can't find problem. Can't access controller.

**Comment by Spambanjo** [comment]
FYI I'm on 3.2.1

**Comment by Edvardas-idea** [comment]
ok so... i have found some kind of workaround but it really isn't good solution 
`Director:
  rules:
    'FacebookConnectAuthCallback': 'FacebookConnectAuthCallback'`

so i got it working, but there's another problem, it creates member but with no fields, empty, not even email. So i found out that this code `                $user = (new FacebookRequest(
                    $session, 'GET', '/me', $fields
                ))->execute()->getGraphObject(GraphUser::className());`

returns me only name and id of facebook user. could the problem be with sdk itself ?

**Comment by wilr** [comment]
Have added the rule to the config. Please update and flush your cache to retest.

**Comment by Edvardas-idea** [comment]
the module now works fine, Thanks.
