### ISSUE TITLE
[error] route rules

### ISSUE THREAD

**Issue by alexandruz** [wilr/silverstripe-facebookconnect#30]
Shouldn't it be (in the new config):

```
Director:
  rules:
    'FacebookConnectAuthCallback//$Action/$ID/$OtherID': 'FacebookConnectAuthCallback'
```
https://docs.silverstripe.org/en/3.3/developer_guides/controllers/routing/

(my homepage exploded)

**Comment by wilr** [comment]
Please submit a PR. Whats the different between the current rule and that? AFAIK you need to keep the -

**Comment by alexandruz** [comment]
Although i thought as you did i think this proves it (?) from Director::handleRequest
```
foreach($rules as $pattern => $controllerOptions) {
```

& thanks for the merge
