### ISSUE TITLE
Multiple buttons on same page. Only the last one works

### ISSUE THREAD

**Issue by jberculo** [wilr/silverstripe-facebookconnect#36]
It seems that using multiple buttons on the same page causes only the last button to work, probably because a new request is routed to facebook for each , invalidating the earlier buttons. Would it be a solution to return the same link during the entire request, or would that result in other problems?

**Comment by afoster** [comment]
This issue can be quite insidious. Even if you don't have multiple buttons, but during the course of your page load, something triggers a second call to `FacebookRedirectLoginHelper::getLoginUrl()`, it'll invalidate your button.

The two ways this already happened to me:

1) If the CMS user causes a 404 on say, an image, and your default page template includes a `$FacebookLoginLink`. By way of the browser fetching the 404 page (which the user doesn't even see), it invalidates the login link in the primary document. The workaround here is to remove Facebook login functionality from your error page templates.

2) If a valid document is loaded in an incorrect way (like `background-image: url()` resulting in an attempt to load an html document as an image). Not as easy to address as customising your error page template and sure annoying to debug.

**Comment by afoster** [comment]
I guess what I'm trying to say is that it's brittle enough to be of real concern as a sleeper issue in a site build. Any suggestions for a technical approach?

**Comment by wilr** [comment]
@afoster / @jberculo Thanks for the issue. See how 1fbd66c goes and let me know. I haven't seen any side effects from caching this so far in my test but it's only a simple single page site.

**Comment by afoster** [comment]
Much appreciated @wilr , I will test today.

**Comment by afoster** [comment]
Looks great. Thanks again 👍

**Comment by jberculo** [comment]
Thanks, @wilr. I can't test since I switched jobs since then, but looking at the code (and ignoring all the whitespace changes ;)) it seems to do the trick, with maybe a small caveat. I added a comment.
